auth:
  git:
    username: "admin"
    password: "dummy"
    url: https://github.com
  docker:
    # if specified use the docker config.json style secret like this:
    # https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#configuring-docker-authentication-for-docker
    configJson: ""

serviceaccount:
  enabled: true
  annotations: {}
