domain: ""
jxRequirements:
  ingress:
    domain: "example.com"
    externalDNS: false
    kind: ""
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
image:
  repository: ghcr.io/jenkins-x/knative-serving
  tag: 0.19.24
